# Generated by Django 2.2.1 on 2019-05-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='solicitud',
        ),
    ]
