# Generated by Django 2.2.1 on 2019-05-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_credito', models.CharField(max_length=150, verbose_name='Código de Crédito')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('plazo', models.IntegerField(verbose_name='Plazo (meses)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
            },
        ),
    ]
