# Generated by Django 2.2.1 on 2019-05-21 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_cliente_codigo_credito'),
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
            preserve_default=False,
        ),
    ]
